ARG  GRAALVM_VERSION=latest
ARG  BUSYBOX_VERSION=latest

FROM oracle/graalvm-ce:${GRAALVM_VERSION} as graal
RUN gu install native-image
RUN mkdir -p /fitnesse/target

WORKDIR /fitnesse

COPY target/. target
RUN native-image -jar target/hsac-html-report-generator.jar --static

FROM busybox:${BUSYBOX_VERSION}
WORKDIR /fitnesse
VOLUME /fitnesse/target

ENTRYPOINT ["/fitnesse/hsac-html-report-generator"]
CMD []

COPY --from=graal /fitnesse/hsac-html-report-generator .
